class FabricError(Exception):
    category: str

class AdmissionError(FabricError): ...
class SemanticError(FabricError): ...
class StorageError(FabricError): ...
class IntegrityError(StorageError): ...

class Engine:
    def __init__(self, root: str) -> None: ...
    def admit_json(self, record_json: str) -> str: ...
    def seal_json(self) -> str: ...
    def replay_json(self) -> str: ...
    def validate_json(self) -> str: ...
    def locate_json(self, record_id: str) -> str: ...
    def recovery_json(self) -> str: ...
    def pending_count(self) -> int: ...

__version__: str
